[feat] 기록 객체 저장시 객체 url S3 -> cloudfront
Team-Recordy/Recordy-Server pull request #103
Opened 2024-08-04 16:24 UTC by sebbbin

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #이슈번호

## 👷 **작업한 내용**

## 🚨 참고 사항

2024-08-06 07:43 UTC, jinkonu requested changes
수고하셨습니다~~~
리뷰 읽어주세요!

2024-08-06 07:43 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +        FileUrl fileUrl = FileUrl.of(cloudFrontVideoUrl, cloudFrontThumbnailUrl);
`convertToCloudFrontUrl`이 `FileUrl`을 인자로 받아서 처리하면 코드가 더 깔끔해질 것 같다는 생각이 드는데,
혹시 수정이 가능할까요?

2024-08-06 07:43 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +        // CloudFront 배포 도메인 이름
주석은 최대한 자제해주세요!
코드를 통해서 충분히 이해할 수 있습니다~~~

2024-08-06 11:42 UTC, elive7 reviewed
코드 확인 완 했습니다~~
어려웠을 텐데 수고하셨어요!!!

2024-08-06 11:42 UTC, elive7 commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +
recordy-bucket.s3.ap-northeast-2.amazonaws.com 이런 url은 application.yml에 두고 가져다 쓰는 것이 어떨까요?

2024-08-06 11:42 UTC, elive7 commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +                .fileUrl(fileUrl)
이미 위에서 말씀해주셨지만, 저도 여기소 convertToCloudFrontUrl(fileUrl)로 할 수 있으면 더 좋을 거 같아요!

2024-08-07 04:47 UTC, sebbbin commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +        FileUrl fileUrl = FileUrl.of(cloudFrontVideoUrl, cloudFrontThumbnailUrl);
수정했습니다 !

2024-08-07 04:54 UTC, sebbbin commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +
똑똑이 브레인 천재만재 영앤리치앤프리티걸

2024-08-07 05:41 UTC, jinkonu approved these changes
리뷰 반영해주셔서 감사합니다
수고 많으셨어용!!

2024-08-07 05:42 UTC, merged