[feat] Apple Login 구현
Team-Recordy/Recordy-Server pull request #13
Opened 2024-06-27 04:19 UTC by elive7

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #7 

## 👷 **작업한 내용**

- Apple로부터 받은 PublicKeys 중 클라이언트로부터 받아온 identity token과 맞는 PublicKey를 바탕으로 rsaPublicKey를 추출하고, rsaPublicKey를 가지고 claims를 추출 및 검증하는 로직을 활용해 AuthApplePlatformServiceImpl의 getPlatform 함수를 완성했습니다.

- Apple 로그인 관련 error들은 앞에 Apple을 붙여 구분했습니다.
https://github.com/Team-Recordy/Recordy-Server/blob/e8b352fcbce82e37ee4c89750c20eabaff028dcc/src/main/java/org/recordy/server/auth/message/ErrorMessage.java#L7-L20

## 🚨 참고 사항

- 애플 로그인은 다음과 같은 로직을 거칩니다.
Verify the JWS E256 signature using the server’s public key
Verify the nonce for the authentication
Verify that the iss field contains https://appleid.apple.com
Verify that the aud field is the developer’s client_id
Verify that the time is earlier than the exp value of the token

찾아보니 nonce의 SHA256 해쉬값을 request에서 받아 apple token 속 nonce 값과 대조하는 예제를 찾을 수 있었습니다. (https://katarnios.tistory.com/47) 하지만 현재는 request에서 nonce값을 받아오고 있지 않습니다. 

이에 다른 프로젝트를 찾아본 결과 doorip의 경우 nonce를 활용한 검증 로직 제외, soptit은 nonce,iss,aud 전체 검증 로직을 제외한 것으로 보입니다.
저희 프로젝트에서는 어떤 방식을 적용하는 것이 좋을지 의견 남겨주시면 감사하겠습니다. (nonce 검증 로직을 제외한다면, EncryptUtils class도 지울 것 같습니다.)
 nonce을 응답으로 받지 않더라도, 클라이언트와 nonce 값을 통일할 수 있다면 지금 현재 코드를 유지해도 될 것 같습니다.

- application.yml 업데이트 사항이 있습니다. 이는 노션에 업데이트 해두겠습니다.
- 현재 errorMessage와 AuthException을 auth 밑에 패키지를 생성해서 넣었는데, 네이밍이나 폴더링에 더 좋은 방식이 있다면 알려주세요! (카카오 로그인과 맞출 수 있다면 좋을 것 같습니다.)
- 그밖에 다른 폴더링, 네이밍 관련 질문도 환영합니다.

2024-06-27 07:51 UTC, jinkonu requested changes

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/exception/AuthException.java
> +}
저희 `common/exception`에 `RecordyException` 하나 파서 상속해서 쓰도록 하죠!!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/message/ErrorMessage.java
> +    APPLE_INVALID_IDENTITY_TOKEN_CLAIMS(HttpStatus.UNAUTHORIZED, "Apple OAuth Identity Token의 클레임 값이 올바르지 않습니다."),
오 ..! 좋네요

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleClaimsValidator.java
> +    private String nonce;
좋습니다!
다만, oauth 앞에 auth 한 번 붙여주세요!
이전에 auth 관련해서 만들어둔 값들과 엮어주려고 합니다!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleClaimsValidator.java
> +    }
이 메서드를 테스트해볼 수는 없겠죠..?

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleFeignClient.java
> +
별 건 아니지만 인터페이스 바로 아래 한 줄 띄워주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/exception/AuthException.java
> +    private final ErrorMessage errorMessage;
별 건 아니지만 인터페이스 바로 아래 한 줄 띄워주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/message/ErrorMessage.java
> +    APPLE_INVAILD_JWT(HttpStatus.UNAUTHORIZED, "Apple jwt 토큰이 유효하지 않습니다."),
별 건 아니지만 인터페이스 바로 아래 한 줄 띄워주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleClaimsValidator.java
> +    private static final String NONCE_KEY = "nonce";
별 건 아니지만 인터페이스 바로 아래 한 줄 띄워주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleIdentityTokenParser.java
> +    private static final String IDENTITY_TOKEN_VALUE_DELIMITER = "\\.";
별 건 아니지만 인터페이스 바로 아래 한 줄 띄워주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleIdentityTokenParser.java
> +    private  JwtParser getJwtParser(Key key){
여기 띄어쓰기 private과 JwtParser 사이에 한 번 더 되어 있는 것 같아요..!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleIdentityTokenParser.java
> +    private  JwtParser getJwtParser(Key key){
그리고 괄호랑 브라켓 사이도  `){` 떼주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AuthApplePlatformServiceImpl.java
> +    public final AppleOAuthUserProvider appleOAuthUserProvider;
개인적으로 Provider가 하는 일이 ServiceImpl과 동일하다고 생각하는데 어떻게 생각하실까요?

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/ApplePublicKeys.java
> +    public ApplePublicKey getMatchesKey(String alg, String kid){
getMatchingkey로 변경해주세요!

2024-06-27 07:51 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleOAuthUserProvider.java
> +        }
Validator에서 validate()을 하고 거기서 예외를 던지도록 하면 메서드를 줄일 수 있을 것 같은데, 어떻게 생각하실까요?!

2024-06-27 07:56 UTC, jinkonu commented
본문 읽어보았는데요!
nonce 값의 경우엔 아요에 물어보도록 하죠 ... 참고로 nonce 값을 추가하게 되면 API 엔드포인트를 카카오와 애플 2개로 분기시키는 게 맞다고 생각합니다!

2024-06-27 10:45 UTC, elive7 commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleClaimsValidator.java
> +    private String nonce;
네 그렇게 수정하겠습니다!

2024-06-27 11:21 UTC, elive7 commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleOAuthUserProvider.java
> +        }
네 좋은 것 같습니다!
그렇게 수행했습니다!

2024-06-27 11:22 UTC, elive7 commented on src/main/java/org/recordy/server/auth/service/impl/apple/ApplePublicKeys.java
> +    public ApplePublicKey getMatchesKey(String alg, String kid){
변경했습니다!

2024-06-27 11:22 UTC, elive7 commented on src/main/java/org/recordy/server/auth/service/impl/apple/AuthApplePlatformServiceImpl.java
> +    public final AppleOAuthUserProvider appleOAuthUserProvider;
AppleOAuthUserProvider 제거 후 해당 로직을 AuthApplePlatformServiceImpl에 넣는 것으로 수정했습니다!

2024-06-27 11:23 UTC, elive7 commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleIdentityTokenParser.java
> +    private  JwtParser getJwtParser(Key key){
띄어쓰기 관련 수정 모두 완료했습니다!

2024-06-27 11:35 UTC, elive7 commented on src/main/java/org/recordy/server/auth/service/impl/apple/AppleClaimsValidator.java
> +    }
블로그를 찾아보니 해당 메스트를 테스트하는 로직이 있습니다!
다만, ISS, CLIENT_ID, NONCE 값은 application.yml에 있는 값을 사용하거나, 연결 전 테스트를 위해서는 해당 블로그처럼 생성자를 만들어야 할 것 같습니다.
https://kth990303.tistory.com/437?category=852709
```java
@Component
public class AppleClaimsValidator {
 
    private static final String NONCE_KEY = "nonce";
 
    private final String iss;
    private final String clientId;
    private final String nonce;
 
    public AppleClaimsValidator(
            @Value("${oauth.apple.iss}") String iss,
            @Value("${oauth.apple.client-id}") String clientId,
            @Value("${oauth.apple.nonce}") String nonce
    ) {
        this.iss = iss;
        this.clientId = clientId;
        this.nonce = EncryptUtils.encrypt(nonce);
    }
 
    public boolean isValid(Claims claims) {
        return claims.getIssuer().contains(iss) &&
                claims.getAudience().equals(clientId) &&
                claims.get(NONCE_KEY, String.class).equals(nonce);
    }
}
```

2024-06-27 11:49 UTC, jinkonu approved these changes
LGTM 수고했어!!

2024-07-01 11:32 UTC, sebbbin reviewed
LGTM 너무너무 수고하셨습니다 😉 충돌 잘 해결하시길 ..

2024-07-01 11:40 UTC, merged