[feat] 닉네임 중복확인
Team-Recordy/Recordy-Server pull request #20
Opened 2024-06-30 12:41 UTC by sebbbin

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #19 

## 👷 **작업한 내용**

## 🚨 참고 사항

2024-07-01 06:21 UTC, jinkonu requested changes
전반적으로 깔끔하게 잘 작성하신 것 같아요!
수고하셨고, 리뷰 반영 부탁드립니다 !!

2024-07-01 06:21 UTC, jinkonu commented on src/main/java/org/recordy/server/user/exception/ConflictException.java
> +}
RecordyException 공동 예외 만들게 되었으니,
#14에 대한 커밋 풀 하신 후에 RecordyException 상속하도록 수정해주세요!

2024-07-01 06:21 UTC, jinkonu commented on src/main/java/org/recordy/server/user/message/ErrorMessage.java
> +}
ErrorMessage 합치게 되었으니
동일하게 커밋 풀하신 후에 합쳐주시면 감사하겠습니다...!

2024-07-01 06:21 UTC, jinkonu commented on src/main/java/org/recordy/server/user/repository/impl/UserJpaRepository.java
> +    boolean existsUserByNickname(String nickname);
이거 네이밍 규칙이 틀린 것 같은데 `existsByNickname`으로 변경해주세요!

2024-07-01 06:21 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        }
개인적으로 선호하는 것이긴 한데...
괜찮으시면 if 안에 로직인 한 줄이면 괄호 빼주실 수 있으실까요? 🥺

2024-07-01 08:06 UTC, elive7 approved these changes
확인했습니다!! 
근데 닉네임 정규 표현식으로 검증하는 것은 클라 쪽에서 하기로 했었나요...?

2024-07-02 00:37 UTC, jinkonu approved these changes
LGTM ! ! 고생하셨습니다~~~

2024-07-02 00:38 UTC, merged