[feat] 토큰 리프레시 및 로그아웃 구현
Team-Recordy/Recordy-Server pull request #24
Opened 2024-07-01 10:38 UTC by elive7

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #18 

## 👷 **작업한 내용**

- refreshToken을 헤더로 받아서 accessToken을 재발급하는 로직 작성
- logout으로 요청이 오면 해당 accessToken에 해당하는 Auth를 AuthRepository로부터 삭제하여 로그아웃 구현

## 🚨 참고 사항

- FakeAuthRepository와 FakeUserRepository, FakeContainer에서 오류가 발생하는 것 같은데 테스트 만들면서 수정해보겠습니다
- Auth와 User의 개념이 조금 헷갈리는데 혹시 수정할 부분이 있다면 알려주세요
- 지금 AuthRepository에 accessToken도 함께 저장되어 있는데 만약 재발급 로직에서 새로운 accessToken이 나온다면 해당 Auth도 업데이트시켜서 다시 저장해야 할까요? (accessToken 자체를 서버 내에 저장하고 있어도 되는 것인지도 궁금합니다)

2024-07-01 15:01 UTC, jinkonu requested changes
전반적으로 제가 짜놓은 인프라를 잘 이해해주시고 사용해주신 것 같아서 뿌듯합니다
사소하게 몇 가지 적어드린 것만 확인해주시면 좋을 것 같아요!!

고생많으셨습니다~~~ 하단에는 질문에 대한 답변 드릴게요!
- Auth & User
  - Auth는 User에게 인증 정보를 만들어서 제공하거나, User와 연관된 인증 정보를 조회해주는 객체라고 생각하시면 될 것 같아요!

- 지금 AuthRepository에 accessToken도 함께 저장되어 있는데 만약 재발급 로직에서 새로운 accessToken이 나온다면 해당 Auth도 업데이트시켜서 다시 저장해야 할까요?
  - 그럴 필요는 없을 것 같습니다. 제가 액세스 토큰을 괜히 넣은 것 같기도 하네요 ... 이 부분은 고민해보겠습니다

2024-07-01 15:01 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/AuthTokenService.java
> +    String reissueToken(String refreshToken);
별건아니지만 한 줄 떼지 말고 붙여주셔도 좋을 것 같아요!

2024-07-01 15:01 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/AuthService.java
> +    void signOut(long userId);
별건아니지만 한 줄 떼지 말고 붙여주셔도 좋을 것 같아요!

2024-07-01 15:01 UTC, jinkonu commented on src/main/java/org/recordy/server/auth/service/impl/AuthTokenServiceImpl.java
> +    }
제가 `AuthTokenServiceImpl`을 손보면서 이 부분 조금 달라질 것 같은데 develop 브랜치 리베이스 한 이후에 한 번 봐주실 수 있으실까요?

2024-07-01 15:01 UTC, jinkonu commented on src/main/java/org/recordy/server/user/controller/UserController.java
> +    public ResponseEntity signOut(@AuthenticationPrincipal Principal principal) {
`@AuthenticaitonPrincipal`을 활용해서 `ArgumentResolver`를 만들어주실 수 있으실까요? 고잉 참고해서 해주시면 좋을 것 같아요!

(제가 예전에 이 부분에 대해서 말씀드린 적이 있던 것 같은데, 그 때 제가 틀렸던 것 같습니다...)

2024-07-01 15:01 UTC, jinkonu commented on src/main/java/org/recordy/server/user/controller/UserController.java
> +               .build();
제가 깃허브로 봐서 잘못 본 걸 수도 있긴 하지만,
이 부분 들여쓰기 다른 메서드랑 맞춰주실 수 있으실까요?!

2024-07-03 04:09 UTC, jinkonu approved these changes
테스트 아주 잘 작성하셨습니다
봤을 때는 추가하신 비즈니스 로직을 거의 다 커버할 수 있을 것 같네요
새벽 커밋 봤는데 허슬하시느라 고생 많으셨어요 ㅠ.ㅠ

2024-07-03 04:09 UTC, jinkonu commented on src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
> +        String platfromId = authTokenService.getPlatformIdFromRefreshToken(authToken.getRefreshToken());
여기 오타 한번만 수정해주세요!

2024-07-03 04:09 UTC, jinkonu commented on src/test/java/org/recordy/server/auth/repository/AuthRepositoryIntegrationTest.java
> +    void findByRefeshToken을_통해_존재하지_않는_refresh_token으로_인증_데이터를_조회하면_빈_값을_반환한다() {
여기 오타 `findByRefeshToken` -> `findByRefreshToken`로 수정해주세요~~~

2024-07-03 04:09 UTC, jinkonu commented on src/test/java/org/recordy/server/auth/repository/AuthRepositoryIntegrationTest.java
> +    void findByRefeshToken를_통해_refresh_token으로_인증_데이터를_조회할_수_있다() {
여기 오타 `findByRefeshToken` -> `findByRefreshToken`로 수정해주세요~~~

2024-07-03 04:17 UTC, sebbbin reviewed
Test까지 고생하셨습니다 ! 지금 당장 수정할 것은 아니고 저도 같이 수정해야하는 스웨거 문서작업 부분 안까먹으려고 적어놨습니다 ! 수고하셨어요

2024-07-03 04:17 UTC, sebbbin commented on src/main/java/org/recordy/server/user/controller/UserApi.java
> +                            responseCode = "200",
어제 회의때 말한것처럼 추후에 api에 error경우도 같이 추가하면 좋을 것 같아요

2024-07-03 14:40 UTC, merged