[feat] 회원 등록
Team-Recordy/Recordy-Server pull request #31
Opened 2024-07-03 06:34 UTC by sebbbin

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #30 

## 👷 **작업한 내용**

## 🚨 참고 사항

2024-07-04 08:45 UTC, jinkonu requested changes
잘 읽었습니다!
다만 signUp은 사용자를 수정한다는 것에 유의하셔서 수정해주셔야 할 것 같아요..!

2024-07-04 08:45 UTC, jinkonu commented on src/main/java/org/recordy/server/common/handler/GlobalExceptionHandler.java
> +//    }
이 부분 주석 처리하신 이유가 있을까요?

2024-07-04 08:45 UTC, jinkonu commented on recordy.trace.db
> +select ue1_0.id from users ue1_0 where ue1_0.nickname=? fetch first ? rows only [42104-224]
이거 불필요한 파일 같은데 지워주실 수 있으실까요??

2024-07-04 08:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
가능하면
``` java
ResponseEntity
    .status(HttpStatus.CREATED)
    .build();
```
로 수정해주세요!

2024-07-04 08:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        UserStatus status = (userSignUpRequest.useTerm() && userSignUpRequest.personalInfoTerm()) ? UserStatus.ACTIVE : UserStatus.PENDING;
이 부분 잘 작성하셨어요!
다만 저희 입장에서는 두 동의항목 중 하나라도 동의하지 않았다면 상태를 `PENDING`으로 그대로 두기보다는 예외를 던져서 사용자 가입 로직이 진행되지 못하도록 하는 게 맞다고 생각합니다!

2024-07-04 08:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +                .build();
signIn을 보시면 아시겠지만,
가입되지 않은 사용자를 거기서 이미 가입시키고 save()도 진행하고 있습니다.
따라서 signUp은 사용자를 등록하는 로직이 아닌, 사용자를 수정하는 로직이라고 생각하셔야 해요..!

2024-07-04 08:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        }
`{}` 지워주실 수 있으실까요!

2024-07-05 00:08 UTC, sebbbin commented on src/main/java/org/recordy/server/common/handler/GlobalExceptionHandler.java
> +//    }
@jinkonu 에러가 나서 잠시 주석차리 했는데 주석풀고 에러해결해서 넣겠습니닷 !

2024-07-05 00:08 UTC, sebbbin commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        UserStatus status = (userSignUpRequest.useTerm() && userSignUpRequest.personalInfoTerm()) ? UserStatus.ACTIVE : UserStatus.PENDING;
네 !

2024-07-05 00:08 UTC, sebbbin commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +                .build();
아 다시 이해하고 수정하겠습니닷

2024-07-05 00:08 UTC, sebbbin commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        }
https://naver.github.io/hackday-conventions-java/#braces-knr-style

<img width="1047" alt="image" src="https://github.com/Team-Recordy/Recordy-Server/assets/94737768/3b73634a-05a9-4a20-9159-10c2a4b5436e">

2024-07-05 00:10 UTC, sebbbin commented on src/main/java/org/recordy/server/common/handler/GlobalExceptionHandler.java
> +//    }
제가 맘대로 메세지 바궈서 에러였습니다 하하

2024-07-05 01:45 UTC, jinkonu requested changes
다시 한 번 수정 요청드리겠습니다!
고생하셨고~ 고생해주셔야겠슴다 🥹🥹

2024-07-05 01:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
> +        String platformId,
`UserSignInResponse`에서 `platformId`를 반환하지 않기 때문에,
클라 측에서 이 값을 모를 거에요... 혹시 왜 사용하시려는 건지 여쭤봐도 될까요?

2024-07-05 01:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        }
이 부분에 `else` 문이 없더라도 될 것 같습니다!
그냥 `throw` 문만 적어주셔도 될 것 같아요!

2024-07-05 01:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        existingUser.setPersonalInfoTerm(userSignUpRequest.personalInfoTerm());
개인적으로 setter를 호출하는 건 좋지 못하다고 생각합니다...
setter로 바꿔서는 안되는 값까지 전부 바꿀 수 있게 되는 데다가, 이렇게 setter를 나란히 늘여놓는 것은 메서드 호출의 의미가 별로 드러나지 않는 것 같아요.
그래서 이 4개의 setter 호출을 대신해서 `User` 도메인 안에서 이 값들을 가지는 새로운 `User`를 반환해주는 메서드를 정의해주세요 이름은 `activate`으로요!

2024-07-05 01:45 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        existingUser.setPersonalInfoTerm(userSignUpRequest.personalInfoTerm());
그래서 User와 UserEntity에서도 setter를 제거해주세요!

2024-07-05 01:51 UTC, sebbbin commented on src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
> +        String platformId,
아 저는 회원을 확인하려고 저걸 넣었던건데 `UserSignInResponse`여기에 있는 값으로 수정해서 회원을 확인해도될까요?

2024-07-05 01:51 UTC, sebbbin commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        existingUser.setPersonalInfoTerm(userSignUpRequest.personalInfoTerm());
https://velog.io/@backfox/setter-%EC%93%B0%EC%A7%80-%EB%A7%90%EB%9D%BC%EA%B3%A0%EB%A7%8C-%ED%95%98%EA%B3%A0-%EA%B0%80%EB%B2%84%EB%A6%AC%EB%A9%B4-%EC%96%B4%EB%96%A1%ED%95%B4%EC%9A%94 

아 그래서 setter을 잘 안썼군요 ! 다른 블로그들도 확인해서 이해했습니닷

2024-07-05 01:51 UTC, sebbbin commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        }
네 !

2024-07-05 02:26 UTC, jinkonu approved these changes
LGTM !!

2024-07-05 02:26 UTC, jinkonu commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        return userRepository.save(updatedUser);
좋아요~~~

2024-07-05 02:31 UTC, sebbbin commented on src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
> +        return userRepository.save(updatedUser);
조마조마 했네용 ㅎ ㅎ

2024-07-05 03:43 UTC, jinkonu approved these changes
LGTM ~~~

2024-07-05 03:43 UTC, jinkonu commented on src/main/java/org/recordy/server/user/domain/User.java
> +                .ageTerm(termsAgreement.ageTerm())
바로 이런걸 원했습니다~~~

2024-07-05 04:09 UTC, sebbbin commented on src/main/java/org/recordy/server/user/domain/User.java
> +                .ageTerm(termsAgreement.ageTerm())
아웅 뿌듯하네요 ^^~~~

2024-07-05 06:36 UTC, elive7 reviewed
확인했습니다!
궁금한 점 남겨놨는데 그와는 별개로 merge 하셔도 될 것 같아요!

2024-07-05 06:36 UTC, elive7 commented on src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
> +        Long userId,
여기서 accessToken이 아닌 userId를 받은 이유가 있을까요?

2024-07-05 06:46 UTC, sebbbin commented on src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
> +        Long userId,
@elive7 accessToken이 User 도메인 자체에 없어서 accessToken을 받기 위해서 이걸 매칭시켜줘야 한다 생각했는데 그런데 accessToken을 저희가 따로 DB에 저장하는게 아니니 로직이 복잡해지는 기분이 들더라고요 ! 그런데 userId는 생성이 되고, 이미 테이블에 있는 거니까 상대적으로 무난하고 쉬운 값이라고 생각돼서 가져왔습니닷 ~

2024-07-05 06:47 UTC, merged

2024-07-05 08:12 UTC, elive7 commented on src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
> +        Long userId,
너무 늦었지만 혹시 userId만 바디가 아닌 헤더에 담는 것은 어떨까요?? 이제 보니 다른 함수들은 그렇게 진행했더라구요!! 그냥 제안이니까 편하게 반영하시면 됩니다...