[feat] S3
Team-Recordy/Recordy-Server pull request #37
Opened 2024-07-07 11:48 UTC by sebbbin

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #이슈번호

## 👷 **작업한 내용**

## 🚨 참고 사항

2024-07-08 07:05 UTC, jinkonu requested changes
<img width="821" alt="스크린샷 2024-07-06 오후 1 42 31" src="https://github.com/Team-Recordy/Recordy-Server/assets/137763434/1a052fb2-ddad-4307-9169-591d29688ff2">

위 설계를 참고하셔서 FileService를 활용해서 수정해주시기를 부탁드립니다...
그리고 참고사항에 써주신 S3Client에 대해서는 모킹하는 방향으로 바꿔주시면 좋을 것 같아요!!

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/controller/S3TestApi.java
> +public interface S3TestApi {
저 개인적으로 궁금한 게 이 API는 클라 측에도 사용을 해보도록 하기 위해서
이렇게 작성하신 걸까요?!

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/exception/ExternalException.java
> +}
이 부분은 S3Service에 말씀드린 것과 같은 이유로 수정해주셔야 할 것 같습니다...

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/S3Service.java
> +}
정말 잘 작성하셨어요!
그치만 저희가 설계해둔 FileService 안에서 S3Service의 내용이 들어갈 수 있으면 좋을 것 같아요...
FileService 쪽 참고 부탁드릴게요!!

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/S3Service.java
> +}
그리고 인터페이스에는 모든 메서드를 정의하기보다는,
이 S3라는 외부 스토리지를 사용하는 쪽에서 필요한 행동만 제공하는 쪽이 좋아요!

예를 들어, 썸네일이나 영상의 확장자를 업로드할 때 확인하기만 하면 된다면
S3Service를 사용하는 RecordService 쪽에서는 validateImageExtension이나 validateVideoExtension이 제공될 필요가 없습니다..!

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +    public String uploadImage(String directoryPath, MultipartFile image) throws IOException {
S3 내에서 어디에 저장될지는 S3가 직접 정하도록 하는 게 어떠세요?
(`directoryPath`를 매개변수로 받아야 하는가에 대해서 한 번 생각해보시기를 부탁드려요!)

그렇지만 유연한 설계를 위해 노력하신 모습에 대해서는 꼭 칭찬을 드리고 싶습니다!!

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/S3Service.java
> +}
그리고 저희가 모든 영상에 대해 모든 썸네일이 무조건 들어가기 때문에,
(썸네일 혹은 영상만 저장하는 경우가 전혀 없을 것으로 예상되기 때문에)
FileService의 FileUrl save(File file)을 활용해주시기를 부탁드립니다... 🥹🥹

2024-07-08 07:05 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +    }
이 네 개의 메서드는 확장자를 확인하는 메서드 1개와 사이즈를 확인하는 메서드 1개로 줄여주실 수 있을까 합니다..!
그리고 파라미터에 contentType 혹은 size를 넣어주시면 될 것 같아요..!

2024-07-08 09:44 UTC, sebbbin commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +    public String uploadImage(String directoryPath, MultipartFile image) throws IOException {
<img width="267" alt="image" src="https://github.com/Team-Recordy/Recordy-Server/assets/94737768/cd70b49b-0352-4c38-9d89-4bbf66bf9852">

2024-07-08 10:15 UTC, sebbbin commented on src/main/java/org/recordy/server/external/controller/S3TestApi.java
> +public interface S3TestApi {
제가 제대로 되는지 확인하려고 작성했습니다.ㅎㅎ

2024-07-09 00:54 UTC, sebbbin commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +    }
@jinkonu validateVideoExtension의 경우 String contentType = video.getContentType().toLowerCase();이렇게 가져오는데 contentType를 파라미터에 넣어줘야할까요?

2024-07-09 01:39 UTC, sebbbin commented on src/main/java/org/recordy/server/external/exception/ExternalException.java
> +}
@jinkonu 다른건 이해가 됐는데 이부분은 이해가 되지 않아서 S3서비스내에서 사용될 예외처리용 클래스인데 어떤식으로 수정해줘야할까요?

2024-07-09 01:41 UTC, sebbbin commented on src/main/java/org/recordy/server/external/service/S3Service.java
> +}
반영해서 수정했습니다 !

2024-07-09 02:08 UTC, sebbbin commented on src/main/java/org/recordy/server/external/service/S3Service.java
> +}
validateImageExtension는 test코드 작성하려고 인터페이스에 넣었는데 다른 방법 있을까요?

2024-07-09 02:53 UTC, jinkonu commented on src/main/java/org/recordy/server/external/controller/S3TestApi.java
> +public interface S3TestApi {
그러면 이 API로 올린 영상과 썸네일도 실제 S3에 들어가게 되는 걸까요?

2024-07-09 02:54 UTC, jinkonu commented on src/main/java/org/recordy/server/external/exception/ExternalException.java
> +}
S3를 external이 아닌 레코드 도메인에 넣게 되면서 자연스럽게 RecordException에 포함될 것 같다는 말이었는데 제가 설명을 이상하게 했네요 ... 죄성함다

2024-07-09 02:57 UTC, sebbbin commented on src/main/java/org/recordy/server/external/controller/S3TestApi.java
> +public interface S3TestApi {
네 ! 실제로 s3에 들어가는지 확인해보는 용도 였습니다 비디오, 이미지 둘 다 버킷에 잘 들어갔어요

2024-07-09 03:03 UTC, jinkonu approved these changes

2024-07-09 03:03 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +    }
두 메서드의 로직이 거의 비슷하기 때문에 upload라는 이름으로 하나의 메서드로 합쳐주실 수 있으실까요?

2024-07-09 03:03 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +    }
이 부분도 generateFileName으로 하나의 메서드로 두면 좋을 것 같아요

2024-07-09 03:03 UTC, jinkonu commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +        }
여기는 동일한 MAX_SIZE를 적용해도 괜찮은가요?

2024-07-09 03:03 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/impl/FileServiceImpl.java
> +        }
GOOOOOOOOOOOOOOD

2024-07-09 03:03 UTC, jinkonu commented on src/test/java/org/recordy/server/external/controller/S3TestControllerTest.java
> +        String result = s3TestController.uploadImageTest(image);
테스트 때 업로드한 이미지를 다시 제거할 수는 없을까요? 테스트로 인해 데이터가 쌓이개 되는 것을 방지하고 싶어서요!

2024-07-09 03:03 UTC, jinkonu commented on src/test/java/org/recordy/server/external/service/S3ServiceTest.java
> +public class S3ServiceTest {
테스트 작성 감사합니다 !!

2024-07-09 03:03 UTC, jinkonu commented on src/test/java/org/recordy/server/mock/FakeContainer.java
> +        this.s3Service = mock(S3Service.class);  // S3Service mock 사용
GOOOOOOOOOOOOOOOOD

2024-07-09 06:14 UTC, sebbbin commented on src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
> +        }
-합의 완-

2024-07-09 08:50 UTC, sebbbin commented on src/test/java/org/recordy/server/external/controller/S3TestControllerTest.java
> +        String result = s3TestController.uploadImageTest(image);
모킹 방법을 사용하면 따로 이미지가 쌓이지 않는대요 !

2024-07-09 12:06 UTC, merged