[feat] RecordService 1차 구현
Team-Recordy/Recordy-Server pull request #38
Opened 2024-07-07 16:53 UTC by elive7

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #36 
## 👷 **작업한 내용**

-  RecordService.getRecentRecordsByUser 구현
- RecordService에 delete(long recordId) 정의 및 구현

## 🚨 참고 사항

- 지금은 테스트 코드 작성 중...

2024-07-09 16:47 UTC, jinkonu requested changes
수고하셨습니다~~~

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +                .collect(Collectors.toList());
이 로직을 `RecordCreate`에 넣어주세요!
`RecordCreate`에서는 `uploaderId`와 `RecordCreateRequest`를 파라미터로 받으면 될 것 같습니다.

그리고 스트림으로 하나씩 fromString 호출하는 대신에 List<String> keywords를 받아서 Keyword 안에서 List<Keyword>로 변환해주세요!

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +            @RequestPart File file){
`){`을 다른 메서드와 통일해서 포맷팅해주세요!

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +            @PathVariable Long recordId
`@PathVariable`을 사용하셨는데 `@DeleteMapping`의 속성값으로 `("/{recordId})`를 넣어주셔야 스프링 MVC에서 매핑해줄 수 있습니다!

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +            @RequestParam(required = false) List<String> keywords) {
파라미터 중에서 `keywords`를 제일 위로 올려주세요!

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +        }
컨트롤러에서 이 로직을 넣는 것보다는 서비스 안에서 사용해주시기를 부탁드립니다!

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/domain/Record.java
> +        }
우아한테크코스에서는 else를 금지시키는 조건이 있습니다...
저도 개인적으로 지금과 같이 else가 불필요할 때에는 else를 사용하지 않는 것을 권장드려요

2024-07-09 16:47 UTC, jinkonu commented on src/main/java/org/recordy/server/record/repository/RecordRepository.java
> +    Optional<Record> findById(long recordId);
`// query` 하단으로 옮겨주세요

2024-07-09 16:47 UTC, jinkonu commented on src/test/java/org/recordy/server/util/DomainFixture.java
> +                2,
여기 2로 한 이유가 있을까요?

2024-07-10 05:15 UTC, jinkonu requested changes
LGMT !!
거의 다 왔습니다~~~

2024-07-10 05:15 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +        Slice<Record> records = recordService.getRecentRecords(keywords, cursorId, size);
다른 메서드와 형식을 맞춰주면 좋을 것 같아요!
`ResponseEntity.ok().body()`로 해주세요!

2024-07-10 05:15 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +
여기도 마찬가지로 형식 맞춰주세요!!

2024-07-10 05:15 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +        }
else를 제외하고도 돌아갈 수 있는 로직은 else를 제거해주시면 좋을 것 같아요!
(저도 이유는 모르는데 우테코에서 그렇게 하더랍니다...)

2024-07-10 05:46 UTC, elive7 commented on src/test/java/org/recordy/server/util/DomainFixture.java
> +                2,
createRecordCreate()는 유저가 1인데, userId에 따라 필터링하는 것이 제대로 되는지 확인해보고 싶어서, 유저가 2인 Record도 만들게 되었습니다! 더 좋은 방법이 있을까요?

2024-07-10 10:18 UTC, sebbbin approved these changes
LGTM

2024-07-10 10:18 UTC, sebbbin commented on src/main/java/org/recordy/server/common/message/ErrorMessage.java
> +    UNAUTHORIZED_DELETE(HttpStatus.UNAUTHORIZED, "삭제가 불가능한 기록입니다.")
사소한 거지만 `UNAUTHORIZED_DELETE_RECORD` 라고 변경하는 거 어떨까요?!

2024-07-10 10:18 UTC, sebbbin commented on src/main/java/org/recordy/server/common/message/ErrorMessage.java
> +    UNAUTHORIZED_DELETE(HttpStatus.FORBIDDEN, "삭제가 불가능한 기록입니다.")
`FORBIDDEN_DELETE_RECORD`라고 하는 거 어떨까요?

2024-07-10 10:18 UTC, sebbbin commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +            @PathVariable Long recordId
헐빠트렸네용 ㅎㅎ

2024-07-10 10:18 UTC, sebbbin commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +        }
새로 메서드를 만들어서 처리해줬는데 괜찮은지 확인해주세요

2024-07-10 10:18 UTC, merged