[fix] 무한 스크롤 레코드 리스트 수정
Team-Recordy/Recordy-Server pull request #64
Opened 2024-07-14 12:10 UTC by elive7

# 🍃 **Pull Requests**

## ⛳️ **작업한 브랜치**
- Resolved: #57 

## 👷 **작업한 내용**

- 필요한 북마크의 정보를 나타내는 RecordInfo를 정의한 Bookmark 여부를 포함한 RecordInfoWithBookmark를 정의하고, 클라이언트에 반환하는 레코드 리스트를 Slice<RecordInfoWithBookmark> 형태로 변환해주었습니다 (RecordStatController, RecordController 변경 및 완성)
- RecordController에 getSubscribingRecordInfosWithBookmarks에 대한 api도 작성해주었습니다
- postman을 통해 관련 api가 제대로 작동함을 확인했습니다.

## 🚨 참고 사항

- RecordInfo와 RecordInfoWithBookmark가 Record와 Record_stat에 모두 쓰이는데 어느 패키지에 넣는 것이 좋을지 고민입니다. 그런데 생각해보니 Record_stat를 리팩토링할 것이라면 나중에 같이 고민해봐도 될 것 같아요! 현재는 RecordInfo와 RecordInfoWithBookmark 모두 Record dto에만 넣은 상태입니다.

2024-07-14 13:09 UTC, jinkonu requested changes
아주 잘 하셨어요!
참고 사항에 작성하신 부분도 대부분 공감하고, 노션 API 문서를 통해서도 알 수 있듯 동일 url(예를 들면 records)인 API는 동일 컨트롤러 -> 서비스를 쓰도록 수정할 예정입니다...
그리고 두번째 말씀하신 부분도 아주 좋은 생각이에요. 왜냐하면 어차피 서비스 안에서 사용하고 있는데 굳이 컨트롤러에 둘 필요 없다고 생각합니다... 다만 그러한 경우에는 Record의 일부 정보만 보여주는  RecordInfo가 굳이 필요하지 않고 Record + isBookmarked로 RecordInfo를 만들고, 이후에 controller의 dto에서 RecordInfoResponse.from(RecordInfo recordInfo)를 통해 Record 중 필요하지 않은 필드를 빼고 response를 만드는 식으로 생각해봐도 좋을 것 같아요!!

2024-07-14 13:09 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +        return ResponseEntity.ok().body(recordInfoWithBookmarks);
이 부분은 Slice 변수 선언 없이 바로 body에 넣으면서 다른 UserController의 메서드랑 형식을 통일해주세요!

2024-07-14 13:09 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/dto/response/RecordInfoWithBookmark.java
> +){
개인적으로 isBookmark와 recordInfo를 분리한게 좋은 선택이었던 것 같아요!

2024-07-14 13:09 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/RecordService.java
> +    Slice<RecordInfoWithBookmark> getSubscribingRecordInfosWithBookmarks(long userId, long cursorId, int size);
서비스 계층에서 RecordInfoWithBookmark로 사용하기보다는,
컨트롤러 계층에서 from을 호출해서 도메인 -> DTO로 변환하는 것을 추천드려요!

2024-07-14 13:09 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/RecordService.java
> +    Slice<RecordInfoWithBookmark> getSubscribingRecordInfosWithBookmarks(long userId, long cursorId, int size);
그래야 다른 컨트롤러, 혹은 다른 메서드에서 서비스를 호출할 때 서비스를 동일하게, 독립적으로 유지할 수 있다고 생각하기 때문입니다~~~

2024-07-14 13:09 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +        });
만약에 제가 말씀드린 대로 컨트롤러 계층에서 get~~~Records와 findBookmarks를 하는 경우에는 이 로직이 좀 더럽게 보일 수 있을 것 같은데, 그럴 땐 public static RecordInfoWithBookmark of(Slice<Record> records, Slice<Boolean> bookmarks)로 메서드 만들어서 호출해도 좋을 것 같습니다!

2024-07-14 15:47 UTC, elive7 commented on src/main/java/org/recordy/server/record/controller/RecordController.java
> +        return ResponseEntity.ok().body(recordInfoWithBookmarks);
반영했습니다!

2024-07-14 16:44 UTC, elive7 commented on src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
> +        });
반영했습니다!

2024-07-14 17:37 UTC, elive7 commented on src/main/java/org/recordy/server/record/service/RecordService.java
> +    Slice<RecordInfoWithBookmark> getSubscribingRecordInfosWithBookmarks(long userId, long cursorId, int size);
반영했습니다!!

2024-07-14 17:47 UTC, elive7 commented
RecordInfo와 RecordInfoWithBookmark를 컨트롤러의 dto.response에 넣을지 usecase로 뺄지에 대해서는 저도 고민을 했었는데, 리팩토링하는 과정에서 RecordInfo와 RecordInfoWithBookmark가 controller에서만 쓰여서 일단 위치를 변경하지는 않았습니다! 
혹시 아직도 위치를 이동하는 것이 좋을 것 같다면 코멘트 주시면 감사하겠습니다

2024-07-14 18:09 UTC, sebbbin commented
findByBookmark 하는거말고 그냥 exist로 하는거 어떨까요?

2024-07-15 02:56 UTC, jinkonu commented
개인적으로 세빈님 판단도 너무 좋네요!
어차피 boolean으로 매핑할 값인데 find보단 exists로 조회하는 것이 더 깔끔한 것 같습니다~~~

2024-07-15 03:00 UTC, jinkonu approved these changes
고생하셨습니다~~~

2024-07-15 03:00 UTC, jinkonu commented on src/main/java/org/recordy/server/record/controller/dto/response/RecordInfoWithBookmark.java
> +    }
굿입니당~~~

2024-07-15 03:00 UTC, jinkonu commented on src/main/java/org/recordy/server/record/service/RecordService.java
> +    Slice<Record> getSubscribingRecords(long userId, long cursorId, int size);
훨씬 깔끔하네요!!

2024-07-15 03:00 UTC, jinkonu commented on src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkRepositoryImpl.java
> +                .collect(Collectors.toList());
이 부분이 서비스의 `findBookmarks`와 겹치는 것 같다고 생각하는데 어떨까요?

2024-07-15 05:15 UTC, elive7 commented on src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkRepositoryImpl.java
> +                .collect(Collectors.toList());
네 확인해서 삭제했습니다

2024-07-15 05:37 UTC, jinkonu approved these changes
LGTM!!! 수고햇어요

2024-07-15 05:55 UTC, merged